//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXTreelist0904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTalepler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminTalepler()
        {
            this.Dosyalar = new HashSet<Dosyalar>();
            this.TalepDetaylar = new HashSet<TalepDetaylar>();
        }
    
        public int TalepId { get; set; }
        public Nullable<int> yanitId { get; set; }
        public Nullable<System.DateTime> TalepTarihi { get; set; }
        public string Baslik { get; set; }
        public string IsTanim { get; set; }
        public Nullable<int> IsYuzde { get; set; }
        public string TalepDurumu { get; set; }
        public string IsDurumu { get; set; }
        public Nullable<System.DateTime> IseBaslananTarih { get; set; }
        public Nullable<System.DateTime> TahminiBitisTarihi { get; set; }
        public Nullable<int> TerminGunu { get; set; }
        public Nullable<double> HarcananSure { get; set; }
        public Nullable<int> adminId { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<int> acilId { get; set; }
    
        public virtual Aciliyetler Aciliyetler { get; set; }
        public virtual Adminler Adminler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dosyalar> Dosyalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalepDetaylar> TalepDetaylar { get; set; }
    }
}
