//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXTreelist0904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalepDetaylar
    {
        public int tDetayId { get; set; }
        public Nullable<System.DateTime> DetayTarih { get; set; }
        public string DetayTanim { get; set; }
        public Nullable<int> adminId { get; set; }
        public Nullable<int> talepId { get; set; }
    
        public virtual Adminler Adminler { get; set; }
        public virtual AdminTalepler AdminTalepler { get; set; }
    }
}
